apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker
  namespace: event-streaming-messaging-broker
spec:
  acceptors:
    - name: artemis_acceptor
      protocols: 'artemis,core,openwire'
      port: 61616
      sslEnabled: false
    - name: amqp_acceptor
      protocols: amqp
      port: 5672
      sslEnabled: false
  deploymentPlan:
    size: 1
    persistenceEnabled: false
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
