apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    annotations:
      olm.providedAPIs: ActiveMQArtemis.v2alpha1.broker.amq.io,ActiveMQArtemisAddress.v2alpha1.broker.amq.io,ActiveMQArtemisScaledown.v2alpha1.broker.amq.io
    generation: 1
    name: event-streaming-messaging-broker-sub
    namespace: event-streaming-messaging-broker
    resourceVersion: "164848623"
  spec:
    targetNamespaces:
    - event-streaming-messaging-broker
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  name: amq-broker
  namespace: event-streaming-messaging-broker
  resourceVersion: '164848592'
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: amq-broker
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq-broker-operator.v0.9.1
